workflows:
  build-android-ios:
    name: Build Android AAB & iOS Runner.zip
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      vars:
        APP_ID: com.example.yourapp  # <-- Change to your actual app ID
    triggering:
      events:
        - push
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
      - name: Build Android AAB
        script: |
          flutter build appbundle --release
      - name: Build iOS Archive
        script: |
          flutter build ios --release --no-codesign
    artifacts:
      - build/app/outputs/bundle/release/app-release.aab
      - build/ios/iphoneos/Runner.app
      - build/ios/archive/Runner.zip
